spring.application.name=Second Brain Server

# JWT Settings
# This is a default secret key. Please change it in a production environment.
jwt.secret=c2Vjb25kLWJyYWluLXNlcnZlci1zZWNyZXQta2V5LWZvci1qd3QtYXV0aGVudGljYXRpb24tYW5kLWF1dGhvcml6YXRpb24K
jwt.access-token-expiry-ms=86400000

# Google OAuth Settings
# This is a placeholder client ID. Please replace with your actual Google OAuth client ID.
google.client.id=423908552961-v70di4r6o5ed9u0en4i0kg4ataolbf87.apps.googleusercontent.com

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/secondbrain_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Gemini API Key
gemini.api.key=AIzaSyBnIoO0jKmhHd7UfNlpY9_HWq3WN23Y4kg

# Gemini API Base URL
gemini.api.base-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent

# Gemini API Model
gemini.api.model=gemini-pro
